mysite/blog/urls.py
from django.urls import path
from .views import (
        PostDetail,
        PostUpdateView,
        PostDeleteView,
        getblogs,
        home,
        about,
        post_create,
        Profileview,
        PostLikeToggle, 
        PostLikeAPIToggle,
    )


urlpatterns = [
    path("", home, name="blog-home"),
    path("ajax/getBlogs", getblogs, name="getBlogs"),
    path("about/", about, name="blog-about"),
    path("profileview/<name>", Profileview, name="blog-profile"),
    path("post/<slug:slug>/", PostDetail, name="post-detail"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("post_create/", post_create, name="post_create"),
    path('post/like/<slug:slug>/', PostLikeToggle.as_view(), name='like-toggle'),
    path('api/like/<slug:slug>/', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from users.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, handler404
handler404 = 'blog.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
    path('profile/', include('users.urls')),
    path('register/', user_views.register,name='register'),
    path('profile/', user_views.profile,name='profile'),
    path('profile/profileUpdate/<pk>/', user_views.profileUpdate,name='profileUpdate'),
    path('profile/edit/', user_views.editProfile, name='editProfile'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'), #For New User Login By Email/User
    #path('login/', auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password_reset.html'),name='password_reset'),
    path('password_reset_sent/',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_form.html'),name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import (
    favourite_add,
    favourite_list,
)

app_name = 'users'

urlpatterns = [
    path('fav/<int:id>/', favourite_add, name='favourite_add'),
    path('favourites/', favourite_list, name='favourite_list'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from .utils import get_read_time
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

# Create your models here.

class TagDict(models.Model):
    tag = models.CharField(max_length=100)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.tag


class Post(models.Model):
    title       = models.CharField(max_length=100)
    content     = RichTextUploadingField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author      = models.ForeignKey(User, on_delete=models.CASCADE)
    image       = models.ImageField(upload_to="blog_images", height_field=None, width_field=None, max_length=None, blank=True)
    view_count  = models.IntegerField(default=0)
    favourites  = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    slug        = models.SlugField(blank=True, null=True)
    tags        = TaggableManager()
    likes       = models.ManyToManyField(User, blank=True, related_name='post_likes')


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

        for tag in self.tags.all():
            tag_dict,_ = TagDict.objects.get_or_create(tag=str(tag))
            tag_dict.count += 1
            tag_dict.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})
     

    class Meta:
        ordering = ["-date_posted"]
        
    def readTIme(self):
        Read_Time=get_read_time(self.content)
        Read_Time = Read_Time[2:-3]
        return Read_Time
    
    def get_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})

    def get_like_url(self):
        return reverse('like-toggle', kwargs={"slug":self.slug})
    
    def get_api_like_url(self):
        return reverse('like-api-toggle', kwargs={"slug":self.slug})

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

mysite/blog/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'image',
            'content',
            'tags',
        ]
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

mysite/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post,Comment
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, RedirectView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import PostForm,CommentForm
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions


# Create your views here.

def getblogs(request):
    queryset = Post.objects.all()
    return JsonResponse({"blogs":list(queryset.values())})


def home(request):
    posts = Post.objects.all()
    search_query = request.GET.get('q')
    if search_query:
        posts = posts.filter(
            Q(title__icontains = search_query) |
            Q(content__icontains = search_query)
        )

    paginator = Paginator(posts, 2)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    # Top 4 most liked blogs, If possible after the feature of like count is added then 
    # add a logic to store all the 4 id's of most liked blogs from the database in a list, then pass all the id's from the list to this 4 query. 
    mostliked1 = Post.objects.get(id=1)
    mostliked2 = Post.objects.get(id=2)
    mostliked3 = Post.objects.get(id=3)
    mostliked4 = Post.objects.get(id=4)

    context={
        'posts': posts,
        'mostliked1':mostliked1,
        'mostliked2':mostliked2,
        'mostliked3':mostliked3,
        'mostliked4':mostliked4,
    }
    return render(request,'blog/home.html', context)


def about(request):
    return render(request,'blog/about.html')


def Profileview(request,name):
    user    = User.objects.get(username=name)
    posts   = user.post_set.all()
    flag    = (request.user==Post.author)
    context={
        'user':user,
        'flag':flag ,
        'posts':posts,
    }
    
    if request.user != user or request.user == user:
        return render(request,'user/profile.html', context)
    else:
        context={
            'posts': Post.objects.all(),
            'flag':flag,
        }
        return render(request,'blog/home.html',context)


def PostDetail(request, slug):
    post = Post.objects.filter(slug=slug).first()
    comments=Comment.objects.filter(post=post).order_by('-id')
    post.view_count = post.view_count + 1
    post.save()

    objects = Post.objects.get(slug = slug)

    fav = bool
    if objects.favourites.filter(id=request.user.id).exists():
        fav = True

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            body = request.POST.get('body')
            name = request.POST.get('name')
            comment = Comment.objects.create(post=post, name=name, body=body)
            comment.save()
            return redirect(request.path)
    else:
        comment_form = CommentForm()

    context = {
        'object': objects,
        'fav': fav,
        'comments' : comments, 
        'comment_form' : comment_form
    }
    return render(request, 'blog/post_detail.html', context)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    success_url = '/'
    fields = ['title', 'image', 'content', 'tags']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author_id = request.user.id
        instance.save()
        form.save_m2m()
        messages.success(request, "Successfully Created")
        return redirect('blog-home')
    context  ={
        "form": form
    }
    return render(request, "blog/post_create.html", context)

#   For 404 Error Handling
def view_404(request, exception):
    return render(request, 'blog/404.html')

class PostLikeToggle(RedirectView):
    def get_redirect_url(self,*args, **kwargs):
        id_ = self.kwargs.get("slug")
        obj = get_object_or_404(Post,slug=id_)
        url_ = obj.get_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                 obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_

class PostLikeAPIToggle(APIView):
    authentication_classes = [authentication.SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, slug=None,format=None):
        obj = get_object_or_404(Post,slug=slug)
        url_ = obj.get_url()
        user = self.request.user
        updated = False
        liked = False
        verb = None
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                verb = 'Like'
                obj.likes.remove(user)
                count = obj.likes.all().count()
            else:
                liked = True
                verb = 'Unlike'
                obj.likes.add(user)
                count = obj.likes.all().count()
            updated = True
        data = {
            "updated":updated,
            "liked":liked,
            "count":count,
            "verb":verb
        }
        print(data)
        return Response(data)

    

mysite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>About Page</h1>
{% endblock%}

mysite/blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'blog/main.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'blog/tagsinput.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'blog/font-awesome.css' %}">

    <title></title>
  </head>
  <body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="/about">About</a>
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'post_create' %}">Post Create</a>
              {% endif %}
              <!--Search Bar-->
              <div class="search-bar">
                <form method="GET" action="/" style="display:inline-block; line-height:24px; border-radius: 80px;">
                  <input type="text" placeholder="Search Blogs..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search Blogs...';}" name ="q" required="" size="29" style="border-radius: 80px; padding: 0px 12px;">
                </form>
              </div>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

              {% if user.is_authenticated %}

              <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile
                      </a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'profile' %}">Dashboard</a>
                          <a class="dropdown-item" href="{% url 'users:favourite_list' %}">My Favourite Blogs</a>
                          <a class="dropdown-item" href="/">Notification</a>
                           <a class="dropdown-item" href="/">Settings</a>
                          <a class="dropdown-item" href="{% url 'password_reset' %}">Change Password</a>
                      </div>
                  </li>
              </ul>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>


    <main role="main" class="container">
      <!--Slider Start-->
      {% block slider%}

      {% endblock %}
      <!--Slider End-->
      <span style="display:inline-block; width: 3px;"></span>
      {% include 'user/message.html' %}
      
      <div class="row">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section filter-section position-sticky">
            <h3>Filter By</h3>
            <hr style="height: 5px;" />
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="check1">
              <label class="custom-control-label" for="check1">Technology</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="check2">
              <label class="custom-control-label" for="check2">Social</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="check3">
              <label class="custom-control-label" for="check3">Finance</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="check4">
              <label class="custom-control-label" for="check4">Others</label>
            </div>
          </div>
          <div class="content-section trending-section position-sticky">
            <h3>Trending</h3>
            <hr />

          </div>
        </div>
      
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    
    
    <script src="{% static '/blog/tagsinput.js' %}"></script>
    <script src="{% static '/blog/main.js' %}"></script>

     <script>
        $(document).ready(function() {
            function updateText(btn, newCount, verb) {
                $('#pTest').text(newCount)
            }
            $(".like-btn").click(function(e) {
                e.preventDefault()
                var this_ = $(this)
                var likeUrl = this_.attr("data-href")
                if (likeUrl) {
                    $.ajax({
                        url: likeUrl,
                        method: "GET",
                        data: {},
                        success: function(data) {
                            var newLikes;
                            if (data.liked) {
                                //add one like
                                updateText(this_, data.count, data.verb)
                                $("#hid").removeClass("fa-heart-o").addClass("fa-heart");
                            } else {
                                //remove one like
                                $("#hid").removeClass("fa-heart").addClass("fa-heart-o");;
                                updateText(this_, data.count, data.verb)
                            }
                        },
                        error: function(error) {
                            alert("Oops! Error Occurred");
                        }
                    })
                }
            })
        })
    </script>
  </body>
</html>

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/blog/templates/blog/post_create.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'blog/post.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'blog/tagsinput.css' %}" type="text/css">
    <title></title>
  </head>
  <body>
      <!-- header starts -->

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}"> 
            <img src="{% static 'blog/png_logo.png' %}" alt="Blogger" width=110 height = 40 class="d-inline-block align-top">
            <!-- <img src="../static/img/png_logo.png" style="height:40px; width:110px;"></img> -->
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <i class="material-icons" style="padding:9px;color: #eae7dc;">home</i>
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <i class="material-icons" style="padding:9px;color: #eae7dc;">group</i>
              <a class="nav-item nav-link" href="#">Communities</a>
              {% if user.is_authenticated %}
              <i class="material-icons" style="padding:9px;color: #eae7dc;">create</i>
              <a class="nav-item nav-link" href="{% url 'post_create' %}">Create Blog</a>
              {% endif %}
              <i class="material-icons" style="padding:9px;color: #eae7dc;">notifications</i>
              <a class="nav-item nav-link" href="#">Notifications</a>
              <!--Search Bar-->
              <div class="search-bar">
                <form method="GET" action="/" style="display:inline-block; line-height:21px; border-radius: 80px; padding:9px 0 0 95px">
                  <input type="text" placeholder="Search Blogs..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search Blogs...';}" name ="q" required="" size="29" style="border-radius: 80px; padding: 0px 12px; font-style:italic ;">
                </form>
              </div>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color: #eae7dc; "><i class="material-icons" style="padding:4px ;color: #eae7dc;">account_circle</i>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  <a href="{% url 'profile' %}">Profile</a><br>
                  <a  href="{% url 'logout' %}">Logout</a>
                  {% else %}
                  <a  href="{% url 'login' %}">Login</a><br>
                  <a  href="{% url 'register' %}">Register</a>
                  {% endif %}
                </ul>
              </li>
            </div>
          </div>
        </div>
      </nav>
    </header>
<!-- header ends -->

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
            <br>
        <h2 id="post_id">Create Post...</h2>
        <br><br>
        <form class="post-form" method="POST" action="" enctype="multipart/form-data">
            <div class="form-group">
                {% csrf_token %}
                <div id="div_id_title" class="form-group">
                    <div class="">
                        <input type="text" name="title" maxlength="100" class="textinput textInput form-control" required="" id="id_title" placeholder="Add A Catchy Title"><!--Here name="" is the name of the fields of model-->
                    </div>
                </div>
                
                <div id="div_id_image" class="form-group"> 
                    <div class='custom-file'>
                        <input type="file" name="image" accept="image/*" class="custom-file-input"  id="id_image">
                        <label class="custom-file-label" for="id_image">Choose File</label>
                    </div>
                </div>
                
                <div id="div_id_content" class="form-group">
                    <label for="id_content" class="" id="label" style='color:#ea584f'>Write your post here...</label>
                    <div class="" style='padding-left:57px'>
                        {{form.media}}
                        {{form.content}}
                    </div>
                </div>

                <div id="div_id_tags" class="form-group"> 
                    <label for="id_tags" class="">Tags: </label>
                        <div class="" style="display: inline-block;">
                            <input type="text" data-role="tagsinput" name="tags" maxlength="100" class="textinput textInput form-control" id="id_tags">
                        </div>
                </div>

                <button type="submit">Create Post</button>
            </div>
        </form> 
        </div> 
      </div>
    </main>
<br>

<!-- footer starts -->
<div id="footer"></div>
<!-- footer ends -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script> 
$(function(){
  $("#footer").load("Footer.html"); 
});
</script> 
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static '/blog/tagsinput.js' %}"></script>
    <script src="{% static '/blog/main.js' %}"></script>
  </body>
</html>

mysite/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form.media }}
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}